name: release
on:
  push:
    branches:
      - "master"
    tags:
      - "**"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: adoptium:1.11.0.22
          apps: sbt
      - uses: olafurpg/setup-gpg@v3
      - name: Import PGP key
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
        run: echo "$PGP_SECRET" | gpg --import
      - run: sbt '+ publish'
